## Name: Mustafa Erdem
## Date : 04/20/2026
## Exercise : Final Project  
###  Newark Liberty International Airport (EWR) – United Airlines Flight Analysis (2025)

This project analyzes United Airlines flight data specifically for departures from Newark Liberty International Airport (EWR) in 2025. The focus is on flight delays, scheduling accuracy, and operational performance.

### Research Questions
- Which United Airlines aircraft (tail numbers) are associated with the highest number of delayed departures from Newark Liberty International Airport in 2025?
- Which destinations have the highest average departure delays for United Airlines flights departing from Newark Liberty International Airport in 2025?
- What are the main causes of delays for United Airlines flights departures from Newark Liberty International Airport in 2025?
- Do longer United Airlines flights tend to experience higher departure delays from Newark Liberty International Airport in 2025?
- Which time periods (morning, afternoon, evening, night) are associated with the highest number of delayed departures for United Airlines flights from Newark Liberty International Airport in 2025?

In [1]:
import pandas as pd

In [2]:
print("Pandas version:", pd.__version__)

Pandas version: 3.0.2

## Data Cleaning: Removing Corrupted Rows

Before loading the dataset into pandas, the file was cleaned by removing the last two rows, which were causing parsing errors.

This step is necessary because the dataset contains corrupted or incomplete lines at the end of the file, which can break CSV parsing.

After removing these rows, the cleaned data is saved into a new file (`clean_file.csv`) and then used for further analysis.

In [3]:
with open("Detailed_Statistics_Departures.csv", "r") as f:
    lines = f.readlines()

with open("clean_file.csv", "w") as f:
    f.writelines(lines[:-2])

##  Removed Rows

The following rows were removed from the dataset because they were causing parsing errors.

In [4]:
for line in lines[-2:]:
    print(line)

 SOURCE: Bureau of Transportation Statistics

In [5]:
df = pd.read_csv("clean_file.csv", skiprows=7)  ## The first 7 rows are skipped because they contain metadata,
                                                ## and the actual data table begins afterward.

# Removed Rows
The following rows were removed from the dataset.

In [6]:
count = 0
for line in lines:
    if count < 7:
        count += 1
        print(line)

Detailed Statistics Departures

Origin Airport: Newark, NJ: Newark Liberty International (EWR)

Airline: United Airlines Inc. (UA)

Month(s): January, February, March, April, May, June, July, August, September, October, November, and December

Day(s): 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30 and 31

Year(s): 2025

##  Dataset Size

The cleaned dataset contains **66,747 flight records**, confirming that the data was successfully loaded and is ready for analysis.

In [7]:
df.shape

(66747, 17)

In [8]:
df.columns  ## The column names were reviewed for clarity and usability.
            ## Long or complex column names may be shortened or standardized to improve readability and make analysis easier.

Index(['Carrier Code', 'Date (MM/DD/YYYY)', 'Flight Number', 'Tail Number',
       'Destination Airport', 'Scheduled departure time',
       'Actual departure time', 'Scheduled elapsed time (Minutes)',
       'Actual elapsed time (Minutes)', 'Departure delay (Minutes)',
       'Wheels-off time', 'Taxi-Out time (Minutes)', 'Delay Carrier (Minutes)',
       'Delay Weather (Minutes)', 'Delay National Aviation System (Minutes)',
       'Delay Security (Minutes)', 'Delay Late Aircraft Arrival (Minutes)'],
      dtype='str')

In [9]:
df.info() ## Only the “Tail Number” column contains missing values.

<class 'pandas.DataFrame'>
RangeIndex: 66747 entries, 0 to 66746
Data columns (total 17 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Carrier Code                              66747 non-null  str
 1   Date (MM/DD/YYYY)                         66747 non-null  str
 2   Flight Number                             66747 non-null  int64
 3   Tail Number                               65850 non-null  str
 4   Destination Airport                       66747 non-null  str
 5   Scheduled departure time                  66747 non-null  str
 6   Actual departure time                     66747 non-null  str
 7   Scheduled elapsed time (Minutes)          66747 non-null  int64
 8   Actual elapsed time (Minutes)             66747 non-null  int64
 9   Departure delay (Minutes)                 66747 non-null  int64
 10  Wheels-off time                           66747 non-null  str
 11  Taxi-Out time (Minutes)                   66747 non-null  int64
 12  Delay Carrier (Minutes)                   66747 non-null  int64
 13  Delay Weather (Minutes)                   66747 non-null  int64
 14  Delay National Aviation System (Minutes)  66747 non-null  int64
 15  Delay Security (Minutes)                  66747 non-null  int64
 16  Delay Late Aircraft Arrival (Minutes)     66747 non-null  int64
dtypes: int64(10), str(7)
memory usage: 8.7 MB

##  Descriptive Statistics Summary

On average, flights have a departure delay of about 15 minutes, while taxi-out time averages around 26 minutes. Most delay categories such as weather, security, and national aviation system delays have very low median values (often 0), indicating that these delays do not occur frequently.

However, the maximum values show significant outliers in several columns (for example, very large departure delays and carrier delays), suggesting that while most flights experience minor disruptions, a small number of flights suffer extreme delays. This difference between average and maximum values highlights variability in airline performance and the impact of exceptional cases.

In [10]:
display(df.describe().round(3))

,Flight Number,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
count,66747.000,66747.000,66747.000,66747.000,66747.000,66747.000,66747.000,66747.000,66747.000,66747.000
mean,1582.867,223.546,214.620,15.345,26.279,4.918,0.926,5.103,0.002,8.314
std,697.150,93.832,97.658,54.233,16.384,24.433,14.673,18.952,0.526,34.999
min,42.000,65.000,0.000,-32.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,1184.000,160.000,152.000,-6.000,17.000,0.000,0.000,0.000,0.000,0.000
50%,1625.000,193.000,192.000,-3.000,22.000,0.000,0.000,0.000,0.000,0.000
75%,2151.000,288.000,288.000,11.000,29.000,0.000,0.000,0.000,0.000,0.000
max,3012.000,687.000,721.000,1240.000,379.000,899.000,871.000,654.000,136.000,1112.000

In [11]:
display(df)

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,UA,01/01/2025,211,N828UA,BNA,17:29,17:21,157,156,-8,17:46,25,0,0,0,0,0
1,UA,01/01/2025,212,N69819,TPA,20:25,20:34,185,213,9,21:34,60,9,0,28,0,0
2,UA,01/01/2025,293,N38446,RSW,06:45,06:38,195,179,-7,06:52,14,0,0,0,0,0
3,UA,01/01/2025,363,N76054,HNL,09:05,09:09,684,664,4,09:33,24,0,0,0,0,0
4,UA,01/01/2025,403,N27252,FLL,10:00,10:11,197,186,11,10:31,20,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66742,UA,12/31/2025,2678,N894UA,JAX,13:00,12:55,162,136,-5,13:12,17,0,0,0,0,0
66743,UA,12/31/2025,2679,N41140,LAX,10:15,10:11,380,353,-4,10:27,16,0,0,0,0,0
66744,UA,12/31/2025,2691,N17306,MIA,20:15,20:12,202,172,-3,20:31,19,0,0,0,0,0
66745,UA,12/31/2025,2692,N12021,LAX,08:40,08:36,365,353,-4,08:56,20,0,0,0,0,0
66746,UA,12/31/2025,2856,N37504,DFW,20:29,20:23,249,219,-6,20:46,23,0,0,0,0,0

## Column Name Cleaning

Column names were cleaned and standardized to improve readability and consistency. This included removing unnecessary text (e.g., "Arrival", "(Minutes)"), shortening terms (e.g., "departure" → "dep", "Number" → "num"), trimming spaces, replacing spaces with underscores, and converting all names to lowercase.

The updated column names are displayed to verify the changes.

In [12]:
df.columns = (
    df.columns
    .str.replace("Arrival", "")
    .str.replace("departure", "dep")
    .str.replace("Number", "num")
    .str.replace("(MM/DD/YYYY)", "")
    .str.replace("(Minutes)", "")
    .str.replace("National Aviation System", "nas")
    .str.strip()
    .str.replace(" ", "_")
    .str.lower())
display(df.columns)

Index(['carrier_code', 'date', 'flight_num', 'tail_num', 'destination_airport',
       'scheduled_dep_time', 'actual_dep_time', 'scheduled_elapsed_time',
       'actual_elapsed_time', 'departure_delay', 'wheels-off_time',
       'taxi-out_time', 'delay_carrier', 'delay_weather', 'delay_nas',
       'delay_security', 'delay_late_aircraft'],
      dtype='str')

## Data Overview and Missing Values

The total number of flights is calculated using the number of rows in the dataset. Additionally, missing values are identified for each column to understand data completeness and detect potential issues before analysis.

In [13]:
total_flights = df.shape[0]
display(df.isna().sum())
print("-" * 50)
print(f"Total flights: {total_flights}")

carrier_code                0
date                        0
flight_num                  0
tail_num                  897
destination_airport         0
scheduled_dep_time          0
actual_dep_time             0
scheduled_elapsed_time      0
actual_elapsed_time         0
departure_delay             0
wheels-off_time             0
taxi-out_time               0
delay_carrier               0
delay_weather               0
delay_nas                   0
delay_security              0
delay_late_aircraft         0
dtype: int64

--------------------------------------------------
Total flights: 66747

In [14]:
df[df.isna().any(axis=1)] # Display rows with any missing values for virtual inspection

,carrier_code,date,flight_num,tail_num,destination_airport,scheduled_dep_time,actual_dep_time,scheduled_elapsed_time,actual_elapsed_time,departure_delay,wheels-off_time,taxi-out_time,delay_carrier,delay_weather,delay_nas,delay_security,delay_late_aircraft
526,UA,01/03/2025,2279,NaN,PBI,13:08,00:00,190,0,0,00:00,0,0,0,0,0,0
613,UA,01/04/2025,1155,NaN,AUS,12:59,00:00,259,0,0,00:00,0,0,0,0,0,0
775,UA,01/05/2025,702,NaN,LAX,20:35,00:00,383,0,0,00:00,0,0,0,0,0,0
1055,UA,01/06/2025,1973,NaN,IAH,12:30,00:00,245,0,0,00:00,0,0,0,0,0,0
1232,UA,01/07/2025,1818,NaN,CLE,08:25,00:00,106,0,0,00:00,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65920,UA,12/27/2025,2044,NaN,RSW,06:55,00:00,196,0,0,00:00,0,0,0,0,0,0
65922,UA,12/27/2025,2075,NaN,PBI,08:59,00:00,194,0,0,00:00,0,0,0,0,0,0
65959,UA,12/27/2025,2444,NaN,FLL,09:15,00:00,199,0,0,00:00,0,0,0,0,0,0
65974,UA,12/27/2025,2669,NaN,TPA,08:59,00:00,186,0,0,00:00,0,0,0,0,0,0
66297,UA,12/29/2025,1960,NaN,SFO,07:00,00:00,380,0,0,00:00,0,0,0,0,0,0

## Identifying Cancelled Flights

Flights with an actual departure time of "00:00" are identified as cancelled or non-departed. These records are filtered, and the total number of cancelled flights is calculated for further analysis.

In [15]:
print(df[df["actual_dep_time"] == "00:00"].shape)
canceled_flights = df[df["actual_dep_time"] == "00:00"].shape[0]
print(f"Canceled flights: {canceled_flights}")

(897, 17)
Canceled flights: 897

## Flight Cancellation Rate

The analysis indicates that approximately `1.34% of flights were classified as cancelled or non-departed`, based on records with no recorded departure activity (e.g., "00:00" actual departure time). These observations were excluded from subsequent analyses to ensure that delay metrics are computed only from completed flights.

In [16]:
df = df[df["tail_num"].notna()]
percentage_canceled = (canceled_flights / total_flights) * 100
print(f"Percentage of canceled flights: {percentage_canceled:.2f}%")

Percentage of canceled flights: 1.34%

In [17]:
df.isna().sum() ## After filtering out canceled flights, there are no missing values in the dataset.

carrier_code              0
date                      0
flight_num                0
tail_num                  0
destination_airport       0
scheduled_dep_time        0
actual_dep_time           0
scheduled_elapsed_time    0
actual_elapsed_time       0
departure_delay           0
wheels-off_time           0
taxi-out_time             0
delay_carrier             0
delay_weather             0
delay_nas                 0
delay_security            0
delay_late_aircraft       0
dtype: int64